Create decorator classes
simplegoose/school-lib pull request #2
Opened 2023-05-16 06:31 UTC by simplegoose

In this PR, the following was done:

- New decorator classes inside the person.rb file

2023-05-16 07:26 UTC, Olamarx requested changes
Hi @simplegoose, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
- All classes created ✔️
- Linters passed ✔️
- Readme file professional ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- I will recommend you create the classes in separate files so that you will use the require_relative to import it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 07:26 UTC, Olamarx commented on person.rb
> +class Person < Nameable
- [ ] The Person class needs to have a class of correct_name too as stated in the project requirement. Kindly implement it.

![image](https://github.com/simplegoose/school-lib/assets/86200356/66e11a8a-482a-4879-97f7-0f22e98a1514)

2023-05-16 07:26 UTC, Olamarx commented on person.rb
> +end
- [x] The Decorator class is supposed to inherit from Nameable class. And you will also need to be able to get and set(read and write) the name.
It would be something more like:
```
class Decorator < Nameable
    attr_accessor :nameable
  
    def initialize(nameable)
      @nameable = nameable
    end
  

    def correct_name
      @nameable.correct_name
    end
end
```

2023-05-16 07:26 UTC, Olamarx commented on person.rb
> +end
- [ ] Upon addressing what I pointed out as regards the Decoration class, you will need to alter this method too as you will work with @nameable and not @person. Something more like `@nameable.correct_name.capitalize`

2023-05-16 07:26 UTC, Olamarx commented on person.rb
> +    @person.name[0...10]
- [ ] I would implore you to do a proper check before you trim the name. What you want to achieve is for this to get trimmed if it is more than 10 characters. You need to check two things:
- Are the letters more than 10? To achieve this, remember array is index based, so it starts from 0 so to get 1 to 10, we will need to reach 9.
- We need a condition that will be like `@nameable.correct_name.length > 10 ? @nameable.correct_name[0..9] : @nameable.correct_name`. Let me know if you need further clarification.

2023-05-17 13:58 UTC, OyePriscilla requested changes
Hi @simplegoose 👏 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Implemented method in Ruby class ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 13:58 UTC, OyePriscilla commented on person.rb
> +end
- [x] As pointed out earlier and according to the requirement, kindly use the `capitalize` method. There is difference between `upcase` and `capitalize` methods in ruby. [Short tutorial on Ruby capitalize method](https://www.geeksforgeeks.org/ruby-string-capitalize-method-2/)👍 
```suggestion
class CapitalizeDecorator < Decorator
  def correct_name
    @nameable.correct_name.capitalize
  end
end
```

2023-05-17 13:58 UTC, OyePriscilla commented on person.rb
> +trimmed_person = TrimmerDecorator.new(person)
- [optional] With this statement I got a wrong output because it's the `decorated_person` that you actually want to trim. ℹ️ 
```suggestion
trimmed_person = TrimmerDecorator.new(decorated_person)
```

2023-05-17 14:16 UTC, OyePriscilla approved these changes
Hi @simplegoose 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Applied `capitalize` method in Ruby ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 14:17 UTC, merged